--- #EC2 AMI find module
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - files/awscred.yml
  tasks:
  - name: Basic provising of an AMi from our Instance
    ec2_ami_find:
     aws_access_key: "{{ aws_id }}"
     aws_secret_key: "{{ aws_key }}"
     region: "{{ aws_region }}"
     owner: self
     ami_tags:
      Name: Mycopyami
     no_result_action: fail
    register: ami_find
   - debug: msg={{ ami_find.result[0].ami_id }}
   - debug: msg={{ ami_find.result[0].name }}
